const colors = {
  backgroundBlue: 'var(--backgroundBlue)',
  backgroundGrey: 'var(--backgroundGrey)',
  primaryBlue: 'var(--primaryBlue)',
  secondaryBlue: 'var(--secondaryBlue)',
  tertiaryBlue: 'var(--tertiaryBlue)',
  errorRed: 'var(--errorRed)',
  successGreen: 'var(--successGreen)',
  additionalWhite: 'var(--additionalWhite)',
  textGrey: 'var(--textGrey)',
  textBlack: 'var(--textBlack)',
  additionalGreen: 'var(--additionalGreen)',
  additionalRed: 'var(--additionalRed)',
  additionalGrey: 'var(--additionalGrey)',
  successGreenHover: 'var(--successGreenHover)',
  errorRedHover: 'var(--errorRedHover)',
  middleGrey: 'var(--middleGrey)',
  additionalOrange: 'var(--additionalOrange)',
  additionalOrange2: 'var(--additionalOrange2)',
  additionalOrange3: 'var(--addtionalOrange3)',
  darkGreen: 'var(--darkGreen)',
  addtionalBlue: 'var(--additionalBlue)',
  hoverPrimaryBlue: 'var(--hoverPrimaryBlue)',
};
export default colors;
